# Generated by Django 4.1 on 2022-08-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='Untitled Note', max_length=255),
        ),
    ]
