# Generated by Django 4.1 on 2022-08-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-date_updated', '-date_added']},
        ),
    ]
